#! /bin/sh

vm=${1}

off=$(virsh -c qemu:///system list --all | grep " ${vm} " | awk '{ print $3}') ;

if ([ "x$off"=="x" ] || [ "x$off" != "xrunning" ]); then
  echo "Starting ${vm}"; 
  virsh -c qemu:///system start ${vm};
  spicy --host=localhost --port=5900;
else
  echo "${vm} is already running";
  spicy --host=localhost --port=5900;
fi
